title: Emilio Barkett
author: Emilio Barkett
url: "https://emiliobarkett.github.io"

markdown: kramdown
kramdown:
  input: GFM
  footnote_nr: 1

permalink: /blog-posts/:year/:month/:title.html

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
